-- 테이블 및 시퀀스 초기화
DROP SEQUENCE BOARDSEQ;
DROP SEQUENCE ANSWERSEQ;
DROP TABLE BOARD;
DROP TABLE ANSBOARD;

-- 테이블 및 시퀀스 생성
CREATE SEQUENCE BOARDSEQ;
CREATE SEQUENCE ANSWERSEQ;
CREATE SEQUENCE FILESEQ;

CREATE TABLE BOARD(
	BOARDSEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(200) NOT NULL, 
	BOARDNO NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL,
	FILENO NUMBER,
	VIEWCNT NUMBER,
	ANSCNT NUMBER
);

CREATE TABLE ANSBOARD(
	BOARDSEQ NUMBER NOT NULL,
	ANSNO NUMBER NOT NULL,
	ID VARCHAR2(200) NOT NULL,
	ANSCONTENT VARCHAR2(2000) NOT NULL,
	ANSREGDATE DATE NOT NULL
);

CREATE TABLE FILES(
	FILENO NUMBER PRIMARY KEY,
	FILESTREAM VARCHAR2(3000),
	FILETITLE VARCHAR2(1000)
)



INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'KH',0,'테스트','테스트중입니다.',SYSDATE,0,0);
INSERT INTO ANSBOARD VALUES(1,ANSWERSEQ.NEXTVAL,'KH','테스트',SYSDATE);
		UPDATE BOARD SET ANSCNT = ANSCNT+1 WHERE BOARDSEQ = 1 ;

INSERT INTO ANSBOARD VALUES(1,ANSWERSEQ.NEXTVAL,'김경선','김경선 테스트',SYSDATE);
		UPDATE BOARD SET ANSCNT = ANSCNT+1 WHERE BOARDSEQ = 1 ;



SELECT * FROM BOARD ORDER BY BOARDSEQ ASC, REGDATE ASC;

SELECT ROWNUM, BOARD.*
FROM (SELECT A.* FROM BOARD A ORDER BY BOARDSEQ ASC) BOARD ;

 			SELECT BOARD.R, BOARD.*
 			FROM
 			(SELECT ROWNUM R, BOARD.*,(SELECT COUNT(*) FROM ANSBOARD WHERE BOARDSEQ=BOARD.BOARDSEQ) AS ANSCNT
 			FROM (SELECT A.* FROM BOARD A ORDER BY A.BOARDSEQ ASC) BOARD) BOARD 
 			WHERE R >= 0 AND R <=10 ;
 	
 			
 			SELECT R, BOARD.*
 			FROM 
 				(SELECT ROW_NUMBER() OVER(ORDER BY BOARDSEQ) AS R, S.BOARDSEQ, S.ID, S.BOARDNO, S.TITLE, S.CONTENT, S.REGDATE, S.VIEWCNT,
 					(SELECT COUNT(*) FROM ANSBOARD WHERE BOARDSEQ=S.BOARDSEQ) AS ANSCNT FROM BOARD S) 
 			BOARD 
 			WHERE R BETWEEN 0 AND 10;
 		
 		SELECT R, BOARD.*
 		FROM 
 			(SELECT ROW_NUMBER() OVER(ORDER BY BOARDSEQ) AS R, S.BOARDSEQ, S.ID, S.BOARDNO, S.TITLE, S.CONTENT, S.REGDATE, S.VIEWCNT,
 					(SELECT COUNT(*) FROM ANSBOARD WHERE BOARDSEQ=S.BOARDSEQ) AS ANSCNT FROM BOARD S
 					WHERE S.TITLE LIKE '%'||'화'||'%') 
 		BOARD 
 		WHERE R >= 0 AND R<= 10
 		
 		
 			SELECT BOARD.BOARDSEQ, BOARD.ID, BOARD.BOARDNO, BOARD.TITLE, BOARD.CONTENT, BOARD.REGDATE, BOARD.VIEWCNT,
 			(SELECT COUNT(*) FROM ANSBOARD WHERE BOARDSEQ=BOARD.BOARDSEQ) AS ANSCNT
 		FROM (SELECT ROWNUM R, A.* FROM BOARD A WHERE A.TITLE = '김경선페이징' ORDER BY BOARDSEQ ASC) BOARD 
 		WHERE R >= 1 AND R<= 10
 		
 		SELECT R, ANSBOARD.*
		FROM 
			(SELECT ROW_NUMBER() OVER(ORDER BY ANSNO) AS R, A.* FROM ANSBOARD A WHERE BOARDSEQ=2)
		ANSBOARD
		WHERE R >= 1 AND R<= 5
 		
 		
 		
SELECT * FROM ANSBOARD;
