-- 회원 테이블
DROP SEQUENCE USER_NO_SEQ;
CREATE SEQUENCE USER_NO_SEQ;

CREATE TABLE USERS (    
    USER_NO INT
    ,USER_ID            VARCHAR2(50)    NOT NULL   
    ,USER_PW            VARCHAR2(100)   NOT NULL
    ,USER_NAME          VARCHAR2(100)   NOT NULL
    ,USER_EMAIL         VARCHAR2(50)    NOT NULL
    ,USER_SEX           VARCHAR2(1)     DEFAULT 'M' NOT NULL
    ,USER_IMG           VARCHAR(100)    DEFAULT 'user/default-user.png' NOT NULL
    ,USER_SIGNATURE     VARCHAR2(500)   DEFAULT 'HELLO!' NOT NULL
    ,USER_POINT         INT DEFAULT 0   NOT NULL
    ,USER_JOIN_DATE     TIMESTAMP DEFAULT SYSDATE NOT NULL
    ,USER_LOGIN_DATE    TIMESTAMP DEFAULT SYSDATE NOT NULL
    ,SESSION_KEY        VARCHAR2(50) DEFAULT 'NONE' NOT NULL
    ,SESSION_LIMIT      TIMESTAMP    
    ,CONSTRAINT MEMBERS_PK PRIMARY KEY(USER_NO)
    ,CONSTRAINT USER_ID_UNIQUE UNIQUE (USER_ID)
    ,CONSTRAINT USER_SEX_CK CHECK (USER_SEX IN('M', 'W'))
);