DROP TABLE FILES;
DROP SEQUENCE FILESEQ;

CREATE SEQUENCE FILESEQ;

CREATE TABLE FILES(
	FILENO NUMBER PRIMARY KEY,
	FILESTREAM VARCHAR2(3000),
	FILETITLE VARCHAR2(1000)
)

SELECT * FROM FILES;